version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  assignees: ["mruoss"]
- package-ecosystem: docker
  directory: "/build"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  assignees: ["mruoss"]
