version: 2
updates:
  # waiting for yarn v2 support https://github.com/dependabot/dependabot-core/issues/1297
#- package-ecosystem: npm
#  directory: "/"
#  schedule:
#    interval: weekly
#  open-pull-requests-limit: 10
#  assignees: ["mruoss"]
- package-ecosystem: docker
  directory: "/build"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  assignees: ["mruoss"]
