---
root: true

parser: "babel-eslint"
parserOptions:
  allowImportExportEverywhere: true
  ecmaFeatures:
    jsx: true

plugins:
  - babel
  - fp
  - lodash-fp
  - react
  - css-modules
  - jasmine

extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:fp/recommended
  - plugin:lodash-fp/recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:css-modules/recommended
  - plugin:jasmine/recommended

settings:
  "import/resolver":
    "babel-module": {}
  "react":
    "version": "16.4"

globals:
  ___DEV___: false
  ___PROD___: false
  APPLICATION_ENV: false
  module: false
  require: false
  window: false

rules:
  accessor-pairs: 2
  block-scoped-var: 2
  complexity: [ 1, 10 ] # 10 is completely arbitrary
  comma-dangle: [2, "always-multiline"]
  consistent-return: 2
  curly: 2
  default-case: 1
  dot-location: [ 2, "property" ]
  dot-notation: 2
  eol-last: 2
  guard-for-in: 1
  # key-spacing: [1, { align: "value" }] doesn't work with object spread
  eqeqeq: [2, "smart"]
  fp/no-delete: 2
  fp/no-let: 1
  # fp/no-mutation: [1, { exceptions: [{ property: "propTypes" }, { property: "contextTypes" }] }]
  fp/no-mutating-methods: [ 1, { allowedObjects: [ 'history' ] }]
  fp/no-nil: 0
  fp/no-rest-parameters: 0
  fp/no-throw: 1
  fp/no-unused-expression: 0
  # to be refactored
  fp/no-mutation: 0
  # until refactoring of components using recompose is completed
  fp/no-class: 0
  fp/no-this: 0
  # max-len:
  #   - 1 # warning
  #   - 80 # line length for code
  #   - 3 # tab width
  #   - ignoreComments: true
  #     ignoreTrailingComments: true
  #     ignoreUrls: true
  #     ignoreStrings: true
  #     ignoreTemplateLiterals: true
  #     ignoreRegExpLiterals: true
  no-eq-null: 0
  no-caller: 2
  no-debugger: 1
  no-case-declarations: 2
  no-div-regex: 2
  no-else-return: 2
#  no-empty-label: 2
  no-empty-pattern: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-fallthrough: 2
  no-floating-decimal: 2
  no-implicit-coercion: 2
  no-implied-eval: 2
  # no-invalid-this: 2
  no-labels: 2
  no-lone-blocks: 2
  no-loop-func: 2
  no-magic-numbers: 0
  no-mixed-spaces-and-tabs: [2, "smart-tabs"]
  no-multiple-empty-lines: [1, {"max": 3, "maxEOF": 1}]
  no-multi-spaces:
    - 1
    - exceptions:
        VariableDeclarator: true
        ImportDeclaration: true
  no-multi-str: 2
  no-native-reassign: 2
  no-param-reassign: [ 1, { "props": false }]
  no-return-assign: [ 1, "always" ]
  no-undef: 1
  no-unexpected-multiline: 2
  no-unused-vars: 1
  # no-var: 2
  object-curly-spacing: [ 2, "always" ]
  semi: [2, "never"]
  valid-jsdoc: 0
  react/display-name: 0
  react/prop-types: 1
  babel/no-invalid-this: 2

env:
  es6: true
  jasmine: true
