export const ADD_HUNDRED = 'ADD_HUNDRED'
export const ADD_FIFITY = 'ADD_FIFITY'
export const ADD_TWENTY = 'ADD_TWENTY'
export const ADD_ONE = 'ADD_ONE'
export const ADD_POINTS = 'ADD_POINTS'
export const RESET_SCORE = 'RESET_SCORE'
