name: Deployment
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install deps
        uses: borales/actions-yarn@v5
        with:
          cmd: install --immutable

      - name: Build App
        uses: borales/actions-yarn@v5
        with:
          cmd: build

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/839825511425/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'gh-actions-jasstafel@wedding-165516.iam.gserviceaccount.com'

      - id: 'upload-dist-folder'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'dist'
          destination: 'jasstafel.michaelruoss.ch'
          parent: false

      - id: 'upload-index-html'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'dist/index.html'
          destination: 'jasstafel.michaelruoss.ch'
          parent: false
          headers: |-
            cache-control: no-store

      - id: 'upload-sw-js'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'dist/sw.js'
          destination: 'jasstafel.michaelruoss.ch'
          parent: false
          headers: |-
            cache-control: no-store

      - id: 'upload-maifest-json'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'dist/manifest.json'
          destination: 'jasstafel.michaelruoss.ch'
          parent: false
          headers: |-
            cache-control: no-store

      - id: 'upload-well-known-folder'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'build/.well-known'
          destination: 'jasstafel.michaelruoss.ch'

      - id: 'upload-privacy-policy'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'build/privacy-policy.md'
          destination: 'jasstafel.michaelruoss.ch'
